#
# Describes the Lambda Function
#

type: lambda-function

name: ShimServiceLiveAgentPoller

description: "Shim Service Live Agent Poller"

#
# The zip file that contains the code.
#
zip-file: "${lambda-zips-dir}/live-agent-poller.zip"

runtime: python3.11

handler: app.handler

#
# Memory size in megabytes
#
memory-size: var.live_agent_poller_lambda_memory_size


#
# Ephemeral storage size in megabytes
#
ephemeral-storage: 512

#
# Time-out, in minutes:seconds, or seconds.
# i.e.
# "15:00" - 15 minutes.
#      10 - 10 seconds.
#
timeout: 60

#
# Log retention for the log group, in days.
#
log-retention-days: 30

layers:
  - common-layer
  - requests-layer

#
# true means create an SQS queue that will trigger this lambda
#
event-queue: false

#
# true to create a mirror lambda function, to allow recursive calls without upsetting AWS.
#
mirror: ${mirroring-enabled:false}

arn-env-name: THIS_FUNCTION_ARN

permissions:

  topics:
    - name: shim-error
      actions:
        - "sns:Publish"

  lambdas:
    - ShimServiceNotificationPublisher
    - ShimServiceLambdaScheduler

  dynamodb-tables:
    - table: ShimServiceSession
      actions:
        - GetItem
        - BatchGetItem
        - PutItem
        - UpdateItem
        - DeleteItem

    - table: ShimServiceVirtualRangeTable
      actions:
        - GetItem
        - BatchGetItem
        - BatchWriteItem
        - PutItem
        - UpdateItem
        - DeleteItem
        - Query

    - table: ShimServiceVirtualTable
      actions:
        - GetItem
        - BatchGetItem
        - BatchWriteItem
        - PutItem
        - UpdateItem
        - DeleteItem

    - table: ShimServiceEvent
      actions:
        - PutItem

environment:
  variables:
    ACTIVE_PROFILES: live-agent-poller
