#
# Describes the Lambda Function
#

type: lambda-function

name: ShimServiceWeb

description: "Shim Service Web Lambda"

#
# The zip file that contains the code.
#
zip-file: "${lambda-zips-dir}/web.zip"

runtime: python3.11

handler: app.handler

#
# Memory size in megabytes
#
memory-size: var.web_lambda_memory_size


#
# Ephemeral storage size in megabytes
#
ephemeral-storage: 512

#
# Time-out, in minutes:seconds, or seconds.
# i.e.
# "15:00" - 15 minutes.
#      10 - 10 seconds.
#
timeout: 90

#
# Log retention for the log group, in days.
#
log-retention-days: 30

layers:
  - common-layer
  - gcp-layer
  - crypto-layer
  - requests-layer

arn-env-name: THIS_FUNCTION_ARN

#
# true means create an SQS queue that will trigger this lambda
#
event-queue: false

mirror: ${mirroring-enabled:false}

permissions:

  lambdas:
    - ShimServiceLiveAgentPoller
    - ShimServiceLambdaScheduler

  secrets:
    - name: shim-service/*
      actions:
        - GetSecretValue

  queues:
    - name: push-notification

  topics:
    - name: shim-error
      actions:
        - "sns:Publish"


  dynamodb-tables:
    - table: ShimServiceSession
      actions:
        - BatchGetItem
        - GetItem
        - PutItem
        - UpdateItem
        - DeleteItem

    - table: ShimServiceVirtualRangeTable
      actions:
        - GetItem
        - BatchGetItem
        - BatchWriteItem
        - PutItem
        - UpdateItem
        - DeleteItem

    - table: ShimServiceVirtualTable
      actions:
        - GetItem
        - BatchGetItem
        - BatchWriteItem
        - PutItem
        - UpdateItem
        - DeleteItem

    - table: ShimServiceEvent
      actions:
        - GetItem
        - PutItem
        - Query



environment:
  variables:
    ACTIVE_PROFILES: web
    CONFIG_SERVICE_URL: ${configServiceUrl:null}
